# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://Jeongm1n.github.io/
baseurl:
title: Jeongmin's blog
author: Jeongmin
description: "조정민의 블로그에 오신 것을 환영합니다."
avatar: profile.png
email: qll4359@email.com
github: Jeongm1n # username
insta: wjdals4_6/?hl=ko
#twitter: username
#linkedin: username
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: https-jeongm1n-github-io
google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]
