# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Jeongmin's blog
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: https://Jeongm1n.github.io
baseurl:

google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "https-jeongm1n-github-io"
disqus_site_shortname: ""

# Author settings
author:
  name: Fernando Moreira
  job: Frontend Engineer
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/author.jpg
  email: qll4359@gmail.com
  url: https://Jeongm1n.github.io
  github: Jeongm1n
  #twitter:
  facebook: profile.php?id=100012240100710
  #linkedin: https://linkedin.com/in/nandomoreirame

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude:
  [
    "config.rb",
    "src",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "README.md",
    "Rakefile",
  ]
